# Generated by Django 4.2.20 on 2025-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
